# Generated by Django 5.1.7 on 2025-03-20 11:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shortenedlink',
            unique_together={('user', 'shortened_url')},
        ),
    ]
