# Generated by Django 5.1.7 on 2025-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_shortenedlink_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortenedlink',
            old_name='original_url',
            new_name='address',
        ),
        migrations.AlterUniqueTogether(
            name='shortenedlink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shortenedlink',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='shortenedlink',
            name='shortened_url',
        ),
    ]
