# Generated by Django 5.1.7 on 2025-03-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_rename_original_url_shortenedlink_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
